import Head from 'next/head';
import classes from '@/styles/pages/Contact.module.scss';
import EmailForm from '@/ui/components/EmailForm/EmailForm';
import ContentCardSocialMedia from '@/ui/components/ContentCardSocialMedia/ContentCardSocialMedia';
import { mediaButtons } from '@/constants/globalConstants';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.container}>
        <EmailForm />
        <ContentCardSocialMedia mediaBtns={mediaButtons} />
      </main>
    </>
  );
}
