import Head from 'next/head';
import classes from '@/styles/pages/Home.module.scss';

export default function Images() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.container}>
        <h1>Contact info</h1>
        <article>Lorem ipsumn</article>
      </main>
    </>
  );
}
