import Head from 'next/head';
import classes from '@/styles/pages/Home.module.scss';
// import Link from 'next/link';
// import { routes } from '@/constants/routes';
import ContentCardIntro from '@/ui/components/ContentCardIntro/ContentCardIntro';
import imgBeard from '@/assets/images/brada.jpg';
import { pages } from '@/constants/globalConstants';
import { routes } from '@/constants/routes';
import IntroButtonsWrapper from '@/ui/components/buttons/IntroButtonsWrapper/IntroButtonsWrapper';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rene Krajnc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.container}>
        {/* <h1>About me:</h1>
        <article>
          I am a software engineer that loves kitties and used to be a soldier.
        </article> */}
        <ContentCardIntro
          title={'Who am I?'}
          text1={
            "My name is Rene and I'm a software engineer specializing in the front end of web development."
          }
          text2={
            "If you'd like to find out more, please take a look at my story or my projects."
          }
          image={imgBeard}
        />
        <IntroButtonsWrapper
          pages={pages.filter((page) => page.route !== routes.HOME)}
        />
      </main>
    </>
  );
}
